[tool.poetry]
name = "njsparser"
version = "1.2"
description = "A Python NextJS data parser from HTML"
authors = ["ae <85891169+novitae@users.noreply.github.com>"]
readme = "README.md"
homepage = "https://github.com/novitae/njsparser"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
lxml = "^5.3.0"
orjson = "^3.10.12"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"